spring.application.name=getp-backend

server.port=8080

google.sheet.url=https://script.google.com/macros/s/AKfycbwGTECRu-a983kn9uhC0FJmPpH3j4ws5bs_qhkvsdJsqSfjAR1qV49_CelDl4FfXB8/exec

app.self.url=https://getp-backend-prod.onrender.com

# Resend API
resend.api.key=${RESEND_API_KEY}
notification.email.to=${NOTIFICATION_EMAIL}