spring.application.name=getp-backend

server.port=8080

google.sheet.url= https://script.google.com/macros/s/AKfycbwGTECRu-a983kn9uhC0FJmPpH3j4ws5bs_qhkvsdJsqSfjAR1qV49_CelDl4FfXB8/exec

app.self.url= https://getp-backend-prod.onrender.com

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

notification.email.from=${SPRING_MAIL_USERNAME}
notification.email.to=${NOTIFICATION_EMAIL}